# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. 

# This workflow will install Deno then run Deno lint and test.
# For more information see: https://github.com/denoland/setup-deno

name: Demo

on:
  push:
    branches: ["PART_1_and_2"]
  pull_request:
    branches: ["PART_1_and_2"]

jobs:
  buids:
      name: Node steps
      runs-on: ubuntu-latest
      steps:
#         - name: buils web app
#           run : |
#             echo "build web app"
#             sleep 10s
#         - uses: convictional/trigger-workflow-and-wait@v1.6.1
#           with:
#             owner: techay-mihir-simform
#             repo: frontend_react 
#             github_token: ${{ secrets.G_ACCESS_TOKEN }}
#             workflow_file_name: root.yml
#             ref: main
#             wait_workflow: true
#             client_payload: '{"ref": "test"}'
        - name: Repository Dispatch
          #uses: peter-evans/repository-dispatch@v2
          uses: convictional/trigger-workflow-and-wait@v1.6.1
          with:
            token: ${{ secrets.G_ACCESS_TOKEN }}
            repository: techay-mihir-simform/frontend_react 
            event-type: my-event
            client-payload: '{"sha": "${{ github.sha }}"}' 
        - run: |
            echo " ${{ github.ref_name }} "
